data:
  train:
    _target_: training.dataset.vos_dataset.VOSDataset
    training: true
    video_dataset:
      _target_: training.dataset.vos_raw_dataset.JSONRawDataset
      img_folder: /home/veesion/People-detector/videos  # Path to video frames
      gt_folder: /home/veesion/People-detector/sam2_dataset  # Path to SAM2 masks
      file_list_txt: /home/veesion/People-detector/sam2_dataset/dataset.txt  # Optional: Provide a file list with selected video samples
      ann_every: 4  # Annotation frequency (adjust if needed)
    sampler:
      _target_: training.dataset.vos_sampler.RandomUniformSampler
      num_frames: 8  # Number of frames per video sequence
      max_num_objects: 10  # Max objects per sequence
      reverse_time_prob: 0.5  # Probability of reversing time order
    transforms: ${video_transforms}  # Use standard video transforms
    shuffle: True
    num_workers: 8
    pin_memory: True
    drop_last: True
    collate_fn:
      _target_: training.utils.data_utils.collate_fn
      _partial_: true
      dict_key: all

experiment_log_dir: /home/veesion/People-detector/video-segmentor/sam2_logs  # Logs and checkpoints stored in the SAM2 repo
