
dataset:
    # PATHS to Dataset
    img_folder: /home/veesion/People-detector/sam2_dataset/JPEGImages # PATH to MOSE JPEGImages folder
    gt_folder: /home/veesion/People-detector/sam2_dataset/Annotations # PATH to MOSE Annotations folder
    file_list_txt: /home/veesion/People-detector/sam2_dataset/dataset.txt # Optional PATH to filelist containing a subset of videos to be used for training
